load data
characterset utf8
append
into table TF_F_USER_PURCHASE
FIELDS TERMINATED BY X'01'
TRAILING NULLCOLS
(BINDSALE_ATTR,EXTRA_DEV_FEE,MPFEE,FEEITEM_CODE,FOREGIFT,FOREGIFT_CODE,FOREGIFT_BACKMODE,AGREEMENT_MONTHS,END_MODE,DEVICE_TYPE,MOBILE_COST,DEVICE_NAME,DEVICE_BRAND,IMEI,LIST_BANK,LIST_FEE,LIST_CODE,CREDIT_ORG,CREDIT_TYPE,CREDIT_CARD_NUM,AGREEMENT,PRODUCT_ID,PACKAGE_ID,STAFF_ID,DEPART_ID,START_DATE DATE "YYYY-MM-DD HH24:MI:SS",END_DATE DATE "YYYY-MM-DD HH24:MI:SS",REMARK char(500) ,ITEM_ID char(512) ,PROV_ID,UNI_FOREGIFT_CODE)