load data
characterset utf8
append
into table TS_B_BILL
FIELDS TERMINATED BY X'01'
TRAILING NULLCOLS
(EPARCHY_CODE,CITY_CODE,NET_TYPE_CODE,SERIAL_NUMBER,BILL_ID,ACCT_ID,USER_ID,CYCLE_ID,INTEGRATE_ITEM_CODE,FEE,BALANCE,PRINT_FEE,B_DISCNT,A_DISCNT,ADJUST_BEFORE,ADJUST_AFTER,LATE_FEE,LATE_BALANCE,LATECAL_DATE DATE "YYYY-MM-DD HH24:MI:SS",CANPAY_TAG,PAY_TAG,BILL_PAY_TAG,DESC_OWE_TAG,VERSION_NO,UPDATE_TIME DATE "YYYY-MM-DD HH24:MI:SS",UPDATE_DEPART_ID,UPDATE_STAFF_ID,CHARGE_ID,WRITEOFF_FEE1,WRITEOFF_FEE2,WRITEOFF_FEE3,BACKUP_INFO,ROLL_BACK_INFO,RSRV_FEE1,RSRV_FEE2,RSRV_FEE3,RSRV_INFO1,RSRV_INFO2,ZK_FEE,PROV_ID,UNI_EPARCHY_CODE,UNI_CITY_CODE,UNI_BILL_PAY_TAG,BALANCE_BACKUP_INFO1,BALANCE_BACKUP_INFO2,CREATE_CYCLE_ID)